version: "3"

services:
    chiadog:
        container_name: chiadog
        image: artjacobson/chiadog-docker:latest
        volumes:
            - ./config:/root/.chiadog
            - /path/to/chia/log:/root/.chia/mainnet/log:ro
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        restart: unless-stopped